/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proiect_java;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jh0nix
 */
public class GUI extends javax.swing.JFrame {
   private int rand=0;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        SERIEL = new javax.swing.JLabel();
        MARIME_BECL = new javax.swing.JLabel();
        INALTIMEL = new javax.swing.JLabel();
        CULOAREL = new javax.swing.JLabel();
        BATERIEL = new javax.swing.JLabel();
        MARIME_BEC = new javax.swing.JTextField();
        SERIE = new javax.swing.JTextField();
        INALTIME = new javax.swing.JTextField();
        CULOARE = new javax.swing.JTextField();
        BATERIE = new javax.swing.JTextField();
        Adaugare = new javax.swing.JButton();
        Stergere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SERIE", "MARIME BEC", "INALTIME", "CULOARE", "BATERIE"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        SERIEL.setText("SERIE");

        MARIME_BECL.setText("MARIME BEC");

        INALTIMEL.setText("INALTIME");

        CULOAREL.setText("CULOARE");

        BATERIEL.setText("BATERIE");

        MARIME_BEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARIME_BECActionPerformed(evt);
            }
        });

        SERIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SERIEActionPerformed(evt);
            }
        });

        INALTIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INALTIMEActionPerformed(evt);
            }
        });

        CULOARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CULOAREActionPerformed(evt);
            }
        });

        BATERIE.setText(" ");

        Adaugare.setText("Adaugare");
        Adaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugareActionPerformed(evt);
            }
        });

        Stergere.setText("Stergere");
        Stergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SERIEL)
                            .addGap(55, 55, 55)
                            .addComponent(SERIE, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MARIME_BECL)
                                .addComponent(INALTIMEL)
                                .addComponent(CULOAREL)
                                .addComponent(BATERIEL))
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(INALTIME)
                                .addComponent(CULOARE)
                                .addComponent(MARIME_BEC)
                                .addComponent(BATERIE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Stergere)
                        .addComponent(Adaugare)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SERIEL)
                    .addComponent(SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MARIME_BECL)
                    .addComponent(MARIME_BEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INALTIMEL)
                    .addComponent(INALTIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CULOAREL)
                    .addComponent(CULOARE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BATERIEL)
                    .addComponent(BATERIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Adaugare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stergere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MARIME_BECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARIME_BECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MARIME_BECActionPerformed

    private void SERIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SERIEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SERIEActionPerformed

    private void INALTIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INALTIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INALTIMEActionPerformed

    private void CULOAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CULOAREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CULOAREActionPerformed

    private void AdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugareActionPerformed
       
        Lampa lampa=new Lampa();
        lampa.setserie(SERIE.getText());
        int marime= Integer.parseInt(MARIME_BEC.getText());
        lampa.setmarime_bec(marime);
        int inaltime= Integer.parseInt(INALTIME.getText());
        lampa.setInaltime(inaltime);
        lampa.setCuloare(CULOARE.getText());
        boolean baterie= Boolean.parseBoolean(BATERIE.getText());
        lampa.setcuBaterie(baterie);
        
       
     tabel.setValueAt(lampa.getserie(), rand, 0);
     
     tabel.setValueAt(lampa.getmarime_bec(),rand,1);
     
     tabel.setValueAt(lampa.getInaltime(), rand, 2);
     tabel.setValueAt(lampa.getCuloare(),rand,3);
     tabel.setValueAt(lampa.getcuBaterie() , rand, 4);        
        rand++;
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_AdaugareActionPerformed

    private void StergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        
    int selectedRow = tabel.getSelectedRow(); 
    if (selectedRow != -1) {
       
        model.removeRow(selectedRow);
    } 
    }//GEN-LAST:event_StergereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adaugare;
    private javax.swing.JTextField BATERIE;
    private javax.swing.JLabel BATERIEL;
    private javax.swing.JTextField CULOARE;
    private javax.swing.JLabel CULOAREL;
    private javax.swing.JTextField INALTIME;
    private javax.swing.JLabel INALTIMEL;
    private javax.swing.JTextField MARIME_BEC;
    private javax.swing.JLabel MARIME_BECL;
    private javax.swing.JTextField SERIE;
    private javax.swing.JLabel SERIEL;
    private javax.swing.JButton Stergere;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
